/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package code.byted.cdp.openapi;

import code.byted.cdp.model.ByteDanceResponseRecordSegShardInfoResp;
import code.byted.cdp.model.ByteDanceResponseSegmentationListResp;
import code.byted.cdp.model.ByteDanceResponseSegmentationOnlineServiceEnableReq;
import code.byted.cdp.model.ByteDanceResponseSegmentationOnlineServiceEnableResp;
import code.byted.cdp.model.ByteDanceResponseSegmentationResp;
import code.byted.cdp.model.ByteDanceResponseSegmentationUploadResp;
import java.io.File;
import code.byted.cdp.model.LegacyManualSegCreateRequest;
import code.byted.cdp.model.LegacySegOpenApiInfoResponse;
import code.byted.cdp.model.LegacyUploadedSegCreateRequest;
import code.byted.cdp.model.SegOpenApiFileUploadResponse;
import code.byted.cdp.model.SimplifiedSegCreateOrUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SegmentationApi
 */
@Ignore
public class SegmentationApiTest {

    private final SegmentationApi api = new SegmentationApi();

    /**
     * 创建离线规则-简化
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createConditionalSegmentTest() throws Exception {
        Integer tenantId = null;
        SimplifiedSegCreateOrUpdateRequest body = null;
        LegacySegOpenApiInfoResponse response = api.createConditionalSegment(tenantId, body);

        // TODO: test validations
    }
    /**
     * 分群ID文件下载
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadSegFileTest() throws Exception {
        Integer tenantId = null;
        Integer segId = null;
        String formatType = null;
        Boolean needEncrypt = null;
        File response = api.downloadSegFile(tenantId, segId, formatType, needEncrypt);

        // TODO: test validations
    }
    /**
     * 创建人工分群
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyCreateManualSegmentTest() throws Exception {
        Integer tenantId = null;
        LegacyManualSegCreateRequest body = null;
        LegacySegOpenApiInfoResponse response = api.legacyCreateManualSegment(tenantId, body);

        // TODO: test validations
    }
    /**
     * 创建上传分群
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyCreateUploadSegmentTest() throws Exception {
        LegacyUploadedSegCreateRequest body = null;
        Integer tenantId = null;
        ByteDanceResponseRecordSegShardInfoResp response = api.legacyCreateUploadSegment(body, tenantId);

        // TODO: test validations
    }
    /**
     * 删除分群
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyDeleteSegmentTest() throws Exception {
        Integer tenantId = null;
        Integer segId = null;
        api.legacyDeleteSegment(tenantId, segId);

        // TODO: test validations
    }
    /**
     * 分群详情
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyGetSegmentTest() throws Exception {
        Integer tenantId = null;
        Integer segId = null;
        ByteDanceResponseSegmentationResp response = api.legacyGetSegment(tenantId, segId);

        // TODO: test validations
    }
    /**
     * 分群列表查看，分页
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyGetSegmentListTest() throws Exception {
        Integer tenantId = null;
        Integer current = null;
        Integer pageSize = null;
        String keyword = null;
        Boolean isSelfSee = null;
        Boolean isOnlySourceReady = null;
        String idType = null;
        String segTypes = null;
        String sourcePlatform = null;
        Boolean isAbaseAvailable = null;
        Boolean isAbaseEnabled = null;
        ByteDanceResponseSegmentationListResp response = api.legacyGetSegmentList(tenantId, current, pageSize, keyword, isSelfSee, isOnlySourceReady, idType, segTypes, sourcePlatform, isAbaseAvailable, isAbaseEnabled);

        // TODO: test validations
    }
    /**
     * 修改人工分群
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void legacyModifyManualSegmentTest() throws Exception {
        Integer tenantId = null;
        Integer segId = null;
        LegacyManualSegCreateRequest body = null;
        api.legacyModifyManualSegment(tenantId, segId, body);

        // TODO: test validations
    }
    /**
     * 修改离线规则-简化
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void modifyConditionalSegmentTest() throws Exception {
        Integer tenantId = null;
        Integer segId = null;
        SimplifiedSegCreateOrUpdateRequest body = null;
        api.modifyConditionalSegment(tenantId, segId, body);

        // TODO: test validations
    }
    /**
     * 分群在线服务开启/关闭
     *
     * 开启/关闭单个分群的在线服务
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void segmentOnlineServiceEnableTest() throws Exception {
        ByteDanceResponseSegmentationOnlineServiceEnableReq body = null;
        Integer tenantId = null;
        Integer segId = null;
        ByteDanceResponseSegmentationOnlineServiceEnableResp response = api.segmentOnlineServiceEnable(body, tenantId, segId);

        // TODO: test validations
    }
    /**
     * 上传分群文件
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadSegFileTest() throws Exception {
        File file = null;
        Integer tenantId = null;
        ByteDanceResponseSegmentationUploadResp response = api.uploadSegFile(file, tenantId);

        // TODO: test validations
    }
    /**
     * 上传人工分群文件
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void uploadSegFileToChTest() throws Exception {
        File file = null;
        Integer tenantId = null;
        SegOpenApiFileUploadResponse response = api.uploadSegFileToCh(file, tenantId);

        // TODO: test validations
    }
}
