/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package code.byted.cdp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IDMReq
 */

@javax.annotation.Generated(value = "code.byted.cdp.client.JavaClientCodegen", date = "2023-07-04T16:56:05.487+08:00[Asia/Shanghai]")
public class IDMReq {
  @SerializedName("id")
  private String id = null;

  @SerializedName("source_entity_name")
  private String sourceEntityName = null;

  @SerializedName("target_entity_name")
  private String targetEntityName = null;

  public IDMReq id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 需要转换的原始id值
   * @return id
  **/
  @Schema(required = true, description = "需要转换的原始id值")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IDMReq sourceEntityName(String sourceEntityName) {
    this.sourceEntityName = sourceEntityName;
    return this;
  }

   /**
   * 需要转换的原始id类型
   * @return sourceEntityName
  **/
  @Schema(required = true, description = "需要转换的原始id类型")
  public String getSourceEntityName() {
    return sourceEntityName;
  }

  public void setSourceEntityName(String sourceEntityName) {
    this.sourceEntityName = sourceEntityName;
  }

  public IDMReq targetEntityName(String targetEntityName) {
    this.targetEntityName = targetEntityName;
    return this;
  }

   /**
   * 转换后的id类型
   * @return targetEntityName
  **/
  @Schema(required = true, description = "转换后的id类型")
  public String getTargetEntityName() {
    return targetEntityName;
  }

  public void setTargetEntityName(String targetEntityName) {
    this.targetEntityName = targetEntityName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IDMReq idMReq = (IDMReq) o;
    return Objects.equals(this.id, idMReq.id) &&
        Objects.equals(this.sourceEntityName, idMReq.sourceEntityName) &&
        Objects.equals(this.targetEntityName, idMReq.targetEntityName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sourceEntityName, targetEntityName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IDMReq {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sourceEntityName: ").append(toIndentedString(sourceEntityName)).append("\n");
    sb.append("    targetEntityName: ").append(toIndentedString(targetEntityName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
