/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package code.byted.cdp.model;

import java.util.Objects;
import java.util.Arrays;
import code.byted.cdp.model.LegacyManualSegmentDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * LegacyManualSegCreateRequest
 */

@javax.annotation.Generated(value = "code.byted.cdp.client.JavaClientCodegen", date = "2023-09-20T16:39:48.664+08:00[Asia/Shanghai]")
public class LegacyManualSegCreateRequest {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sourceIdType")
  private String sourceIdType = null;

  @SerializedName("targetIdType")
  private String targetIdType = null;

  @SerializedName("abaseEnabled")
  private Boolean abaseEnabled = null;

  @SerializedName("sourcePlatform")
  private String sourcePlatform = null;

  @SerializedName("detail")
  private LegacyManualSegmentDetail detail = null;

  public LegacyManualSegCreateRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 分群名称
   * @return name
  **/
  @Schema(required = true, description = "分群名称")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LegacyManualSegCreateRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 分群描述
   * @return description
  **/
  @Schema(description = "分群描述")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public LegacyManualSegCreateRequest sourceIdType(String sourceIdType) {
    this.sourceIdType = sourceIdType;
    return this;
  }

   /**
   * 源ID类型
   * @return sourceIdType
  **/
  @Schema(description = "源ID类型")
  public String getSourceIdType() {
    return sourceIdType;
  }

  public void setSourceIdType(String sourceIdType) {
    this.sourceIdType = sourceIdType;
  }

  public LegacyManualSegCreateRequest targetIdType(String targetIdType) {
    this.targetIdType = targetIdType;
    return this;
  }

   /**
   * 生成ID类型
   * @return targetIdType
  **/
  @Schema(description = "生成ID类型")
  public String getTargetIdType() {
    return targetIdType;
  }

  public void setTargetIdType(String targetIdType) {
    this.targetIdType = targetIdType;
  }

  public LegacyManualSegCreateRequest abaseEnabled(Boolean abaseEnabled) {
    this.abaseEnabled = abaseEnabled;
    return this;
  }

   /**
   * 是否开启分群在线服务
   * @return abaseEnabled
  **/
  @Schema(description = "是否开启分群在线服务")
  public Boolean isAbaseEnabled() {
    return abaseEnabled;
  }

  public void setAbaseEnabled(Boolean abaseEnabled) {
    this.abaseEnabled = abaseEnabled;
  }

  public LegacyManualSegCreateRequest sourcePlatform(String sourcePlatform) {
    this.sourcePlatform = sourcePlatform;
    return this;
  }

   /**
   * 来源平台
   * @return sourcePlatform
  **/
  @Schema(description = "来源平台")
  public String getSourcePlatform() {
    return sourcePlatform;
  }

  public void setSourcePlatform(String sourcePlatform) {
    this.sourcePlatform = sourcePlatform;
  }

  public LegacyManualSegCreateRequest detail(LegacyManualSegmentDetail detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @Schema(description = "")
  public LegacyManualSegmentDetail getDetail() {
    return detail;
  }

  public void setDetail(LegacyManualSegmentDetail detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegacyManualSegCreateRequest legacyManualSegCreateRequest = (LegacyManualSegCreateRequest) o;
    return Objects.equals(this.name, legacyManualSegCreateRequest.name) &&
        Objects.equals(this.description, legacyManualSegCreateRequest.description) &&
        Objects.equals(this.sourceIdType, legacyManualSegCreateRequest.sourceIdType) &&
        Objects.equals(this.targetIdType, legacyManualSegCreateRequest.targetIdType) &&
        Objects.equals(this.abaseEnabled, legacyManualSegCreateRequest.abaseEnabled) &&
        Objects.equals(this.sourcePlatform, legacyManualSegCreateRequest.sourcePlatform) &&
        Objects.equals(this.detail, legacyManualSegCreateRequest.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, sourceIdType, targetIdType, abaseEnabled, sourcePlatform, detail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegacyManualSegCreateRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sourceIdType: ").append(toIndentedString(sourceIdType)).append("\n");
    sb.append("    targetIdType: ").append(toIndentedString(targetIdType)).append("\n");
    sb.append("    abaseEnabled: ").append(toIndentedString(abaseEnabled)).append("\n");
    sb.append("    sourcePlatform: ").append(toIndentedString(sourcePlatform)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
