/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package code.byted.cdp.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OpenAPiInsightReportListResp
 */

@javax.annotation.Generated(value = "code.byted.cdp.client.JavaClientCodegen", date = "2023-08-25T10:31:52.572+08:00[Asia/Shanghai]")
public class OpenAPiInsightReportListResp {
  @SerializedName("reportId")
  private Long reportId = null;

  @SerializedName("reportName")
  private String reportName = null;

  @SerializedName("subjectId")
  private Long subjectId = null;

  @SerializedName("desc")
  private String desc = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("isMine")
  private Boolean isMine = null;

  @SerializedName("isPublic")
  private Boolean isPublic = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  @SerializedName("historyDate")
  private List<String> historyDate = null;

  public OpenAPiInsightReportListResp reportId(Long reportId) {
    this.reportId = reportId;
    return this;
  }

   /**
   * Get reportId
   * @return reportId
  **/
  @Schema(required = true, description = "")
  public Long getReportId() {
    return reportId;
  }

  public void setReportId(Long reportId) {
    this.reportId = reportId;
  }

  public OpenAPiInsightReportListResp reportName(String reportName) {
    this.reportName = reportName;
    return this;
  }

   /**
   * Get reportName
   * @return reportName
  **/
  @Schema(required = true, description = "")
  public String getReportName() {
    return reportName;
  }

  public void setReportName(String reportName) {
    this.reportName = reportName;
  }

  public OpenAPiInsightReportListResp subjectId(Long subjectId) {
    this.subjectId = subjectId;
    return this;
  }

   /**
   * Get subjectId
   * @return subjectId
  **/
  @Schema(required = true, description = "")
  public Long getSubjectId() {
    return subjectId;
  }

  public void setSubjectId(Long subjectId) {
    this.subjectId = subjectId;
  }

  public OpenAPiInsightReportListResp desc(String desc) {
    this.desc = desc;
    return this;
  }

   /**
   * Get desc
   * @return desc
  **/
  @Schema(description = "")
  public String getDesc() {
    return desc;
  }

  public void setDesc(String desc) {
    this.desc = desc;
  }

  public OpenAPiInsightReportListResp creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @Schema(required = true, description = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public OpenAPiInsightReportListResp isMine(Boolean isMine) {
    this.isMine = isMine;
    return this;
  }

   /**
   * Get isMine
   * @return isMine
  **/
  @Schema(description = "")
  public Boolean isIsMine() {
    return isMine;
  }

  public void setIsMine(Boolean isMine) {
    this.isMine = isMine;
  }

  public OpenAPiInsightReportListResp isPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

   /**
   * Get isPublic
   * @return isPublic
  **/
  @Schema(description = "")
  public Boolean isIsPublic() {
    return isPublic;
  }

  public void setIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
  }

  public OpenAPiInsightReportListResp createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(required = true, description = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public OpenAPiInsightReportListResp updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(required = true, description = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public OpenAPiInsightReportListResp historyDate(List<String> historyDate) {
    this.historyDate = historyDate;
    return this;
  }

  public OpenAPiInsightReportListResp addHistoryDateItem(String historyDateItem) {
    if (this.historyDate == null) {
      this.historyDate = new ArrayList<String>();
    }
    this.historyDate.add(historyDateItem);
    return this;
  }

   /**
   * Get historyDate
   * @return historyDate
  **/
  @Schema(description = "")
  public List<String> getHistoryDate() {
    return historyDate;
  }

  public void setHistoryDate(List<String> historyDate) {
    this.historyDate = historyDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenAPiInsightReportListResp openAPiInsightReportListResp = (OpenAPiInsightReportListResp) o;
    return Objects.equals(this.reportId, openAPiInsightReportListResp.reportId) &&
        Objects.equals(this.reportName, openAPiInsightReportListResp.reportName) &&
        Objects.equals(this.subjectId, openAPiInsightReportListResp.subjectId) &&
        Objects.equals(this.desc, openAPiInsightReportListResp.desc) &&
        Objects.equals(this.creator, openAPiInsightReportListResp.creator) &&
        Objects.equals(this.isMine, openAPiInsightReportListResp.isMine) &&
        Objects.equals(this.isPublic, openAPiInsightReportListResp.isPublic) &&
        Objects.equals(this.createdAt, openAPiInsightReportListResp.createdAt) &&
        Objects.equals(this.updatedAt, openAPiInsightReportListResp.updatedAt) &&
        Objects.equals(this.historyDate, openAPiInsightReportListResp.historyDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportId, reportName, subjectId, desc, creator, isMine, isPublic, createdAt, updatedAt, historyDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenAPiInsightReportListResp {\n");
    
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    reportName: ").append(toIndentedString(reportName)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    isMine: ").append(toIndentedString(isMine)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    historyDate: ").append(toIndentedString(historyDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
