/*
 * Copyright 2022 ByteDance and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * CDP开放接口
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2023-02-10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package code.byted.cdp.model;

import java.util.Objects;
import java.util.Arrays;
import code.byted.cdp.model.TendencyStatistics;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * 访问统计-核心指标统计曲线
 */
@Schema(description = "访问统计-核心指标统计曲线")
@javax.annotation.Generated(value = "code.byted.cdp.client.JavaClientCodegen", date = "2023-09-20T16:39:48.664+08:00[Asia/Shanghai]")
public class TendencyStatisticsResp {
  @SerializedName("lineName")
  private String lineName = null;

  @SerializedName("data")
  private List<TendencyStatistics> data = null;

  public TendencyStatisticsResp lineName(String lineName) {
    this.lineName = lineName;
    return this;
  }

   /**
   * 曲线名称
   * @return lineName
  **/
  @Schema(description = "曲线名称")
  public String getLineName() {
    return lineName;
  }

  public void setLineName(String lineName) {
    this.lineName = lineName;
  }

  public TendencyStatisticsResp data(List<TendencyStatistics> data) {
    this.data = data;
    return this;
  }

  public TendencyStatisticsResp addDataItem(TendencyStatistics dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<TendencyStatistics>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * 曲线数据
   * @return data
  **/
  @Schema(description = "曲线数据")
  public List<TendencyStatistics> getData() {
    return data;
  }

  public void setData(List<TendencyStatistics> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TendencyStatisticsResp tendencyStatisticsResp = (TendencyStatisticsResp) o;
    return Objects.equals(this.lineName, tendencyStatisticsResp.lineName) &&
        Objects.equals(this.data, tendencyStatisticsResp.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineName, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TendencyStatisticsResp {\n");
    
    sb.append("    lineName: ").append(toIndentedString(lineName)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
